/* This file was generated by syncqt. */
#ifndef QT_QTPDFIUM_VERSION_H
#define QT_QTPDFIUM_VERSION_H

#define QTPDFIUM_VERSION_STR "5.5.0"

#define QTPDFIUM_VERSION 0x050500

#endif // QT_QTPDFIUM_VERSION_H
